version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3000'
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    command: ['yarn', 'run', 'start:dev']
